/**
 * Upload LLM-generated keyword_sentence to Qdrant tool payloads.
 *
 * Reads tools-keywords.jsonl (generated by scripts/generate-keywords.py)
 * and sets the keyword_sentence field on each Qdrant point by ID.
 * Idempotent — safe to run multiple times (setPayload overwrites).
 *
 * No Memgraph update needed — keyword_sentence is consumed only by
 * BM25 index via loadToolCorpus() which reads from Qdrant.
 *
 * Usage:
 *   pnpm tsx src/upload-keywords.ts <path-to-jsonl>
 *   pnpm tsx src/upload-keywords.ts --dry-run <path-to-jsonl>
 */

import { createReadStream } from 'node:fs';
import { createInterface } from 'node:readline';
import { keywordRowSchema } from '@toolcairn/core';
import { createLogger } from '@toolcairn/errors';
import { COLLECTION_NAME, qdrantClient } from '@toolcairn/vector';

const logger = createLogger({ name: '@toolcairn/indexer:upload-keywords' });

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const filePath = args.find((a) => !a.startsWith('--'));

  if (!filePath) {
    console.error('Usage: pnpm tsx src/upload-keywords.ts [--dry-run] <path-to-jsonl>');
    process.exit(1);
  }

  const client = qdrantClient();

  const rl = createInterface({
    input: createReadStream(filePath, 'utf-8'),
    crlfDelay: Number.POSITIVE_INFINITY,
  });

  let processed = 0;
  let skipped = 0;
  let failed = 0;

  for await (const line of rl) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    let raw: unknown;
    try {
      raw = JSON.parse(trimmed);
    } catch {
      logger.warn({ line: trimmed.slice(0, 80) }, 'Skipping malformed JSON line');
      skipped++;
      continue;
    }

    const parsed = keywordRowSchema.safeParse(raw);
    if (!parsed.success) {
      logger.warn({ errors: parsed.error.issues.map((i) => i.message) }, 'Skipping invalid entry');
      skipped++;
      continue;
    }
    const entry = parsed.data;

    if (dryRun) {
      processed++;
      if (processed % 500 === 0) {
        logger.info({ processed, skipped }, 'Dry run progress');
      }
      continue;
    }

    try {
      await client.setPayload(COLLECTION_NAME, {
        payload: { keyword_sentence: entry.keyword_sentence },
        points: [entry.id],
      });
      processed++;
    } catch (err) {
      logger.error({ id: entry.id, name: entry.name, err }, 'Failed to update Qdrant point');
      failed++;
    }

    if (processed % 500 === 0) {
      logger.info({ processed, failed, skipped }, 'Upload progress');
    }
  }

  logger.info(
    { processed, failed, skipped, dryRun },
    dryRun ? 'Dry run complete' : 'Keyword upload complete',
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
